# Headless service
apiVersion: v1
kind: Service
metadata:
  name: active
  labels:
    name: active
spec:
  ports:
    - port: 8161
      name: active
      targetPort: 8161
      protocol: TCP
  clusterIP: None
  selector:
    name: active
