apiVersion: "v1"
kind: ReplicationController
metadata:
 name: active-pod
 labels:
  name: active-pod
  app: test
spec:
 replicas: 2
 template:
  metadata:
   labels:
    name: active-pod
  spec:
   containers:
    - name: active-pod
      image: agabrieli81/rhel_activemq5_java8:latest
      ports:
       - containerPort: 8161
         name: active-pod
         protocol: TCP
