apiVersion: v1
kind: PersistentVolume
metadata:
  name: active-pv0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/export/1
    server: 10.20.12.218

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: active-pvc0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: active-pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/export/02
    server: 10.20.12.218

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: active-pvc1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: active-pv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/export/03
    server: 10.20.12.218
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: active-pvc2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
