apiVersion: "v1"
kind: Service
metadata:
 name: active
 labels:
  name: active
  app: test
spec:
 selector:
  name: active-pod
 type: NodePort
 ports:
  - port: 8161 ## cluster port
    nodePort: 30001 ## porta del node
    name: active-pod
    targetPort: 8161 ## container port
    protocol: TCP
