apiVersion: "v1"
kind: PersistentVolume
metadata:
 name: active-pv
 labels:
  type: local
spec:
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteMany
 persistentVolumeReclaimPolicy: Retain
 nfs:
  path: "/opt/export"
  server: 10.20.12.218
  readOnly: false
